### ISSUE TITLE
url aus selber tabelle, aber unterschiedliche Artikel

### ISSUE THREAD

**Issue by gegerino** [tbaddade/redaxo_plugin_url_control#21]
HI,

ich habe folgendes Problem:
Ich habe eine Tabelle aus der ich für 2 unterschiedliche Seiten URLs generieren möchte.
Also Artikel news und artikel news2, beide bedienen sich aber an der tabelle news.
Wie kann ich jetzt mit url_generate::getUrlById('rex_news', $news_id), sagen welcher von beiden Artikel verwendet werden soll?

Ich hoffe das war halbwegs verständlich.

Gruß Gegerino

**Comment by tbaddade** [comment]
Verstehe nicht was du erreichen willst. Kannst du das mit genauen Beispielen beschreiben.

**Comment by gegerino** [comment]
Hey, sorry, ich hatte da einen Denkfehler drin...
