### ISSUE TITLE
Backend / Frontend-Links defekt

### ISSUE THREAD

**Issue by alexplusde** [tbaddade/redaxo_plugin_url_control#22]
Wenn man auf "URL erzeugen" klickt und ein URL-Schema erzeugt, dann werden ja zwei Links angezeigt zu Frontend und Backend. Beide funktionieren nicht.

Backend: Man landet in der Struktur, nicht auf dem Artikel
Frontend: Man landet auf der 404-Seite. Die URL müsste logischerweise mit SEO42 erzeugt werden, damit der korrekte Rewrite stattfindet.

**Comment by tbaddade** [comment]
Welche Version verwendest du von SEO42?

**Comment by alexplusde** [comment]
SEO42 4.3.0 
Das war auch schon bei vorangegangen Versionen so (noch vor 4.0). Ich wollte endlich mal das Issue dazu aufmachen :)

**Comment by dpf-dd** [comment]
Kann den Bug bestätigen.
Im Frontendlink schiebt sich ein "redaxo/" rein wo es nicht hingehört. Im Backendlink fehlt die Category-ID und doe Mode-Variable... Sollte leicht zu fixen sein... (getestet mit Redaxo 4.6.2. + SEO42 4.3.0)

**Comment by tbaddade** [comment]
Der eine Bug (Backend) gehört mir der andere Seo42 (Frontend).
Ich nutze rex_getUrl für das Frontend. Das redaxo/ kommt dann vom @RexDude 
https://github.com/tbaddade/redaxo_plugin_url_control/blob/master/pages/url_generate.php#L36

**Comment by RexDude** [comment]
Kann mir einer von euch einen Fix schicken zum 2.Prob?

**Comment by dpf-dd** [comment]
Habe es mal angepasst und das funzt jetzt bei mir (Redaxo 4.6.2 mit SEO42 4.3.0)...
Hier meine Hotfix-Vorschläge:

Korrektur Backend-Link (Link öffnet in gleichem Tab):
Zeile 34:
$return .= '<a href="index.php?page=content&amp;article_id='.$list->getValue('article_id').'&amp;mode=edit&amp;clang='.$list->getValue('clang').'">Backend</a>';

Korrektur Frontend-Link (Link öffnet in neuem Tab):
Zeile 36:
$return .= '<a href="/' . rex_getUrl($list->getValue('article_id'), $list->getValue('clang')) . '" target="_blank">Frontend</a>';

**Comment by tbaddade** [comment]
Die Url zum Frontend mit Seo42 anpassen nicht das Plugin. Es kann ansonsten so etwas entstehen `/http://muldtidomain/article.html`

**Comment by dpf-dd** [comment]
Öhm, da würde ich glatt widersprechen!? Der Die Webserver-Adresse wird doch automatisch vor den Rootslash gesetzt, ganz egal auf welcher Domain das läuft? Oder unterliege ich einem Denkfehler?

**Comment by tbaddade** [comment]
>  Oder unterliege ich einem Denkfehler?
yrewrite gibt ganze Urls zurück, wenn ein Artikel zu einer anderen Domain gehört.

**Comment by dpf-dd** [comment]
Hmmkay. JETZT sehe ich nicht mehr durch :D
SEO42 und yRewrite sind doch 2 paar Schuhe. Man nimmt doch immer nur eins von beiden. Und da url_control für SEO42 ist, warum soll ich dann auf irgendwelche Eigenheiten von yRewrite eingehen?

**Comment by tbaddade** [comment]
https://github.com/tbaddade/redaxo_plugin_url_control#unterstützte-rewriter

**Comment by dpf-dd** [comment]
OK, das hab ich übersehen. Aber dann bin ich mit meinem Latein leider am Ende...

Problem ist ja, dass der Frontend-Link aus dem Backend aufgerufen wird (was recht selten der Fall ist, hier aber halt gebraucht wird). "rex_getUrl" unterscheidet das aber nicht, der hängt einfach den relativen Pfad an die aktuelle Umgebung an - und so rutscht hier das "/redaxo" rein, wenn ich mich im Backend befinde... :(

Die Alternative wäre, statt dem relativen "rex_getUrl" z.B. das absolute "seo42::getFullUrl" zu nehmen, doch leider führt das halt zu folgender Ausgabe: `http://www.test.de/http://www.test.de/`

Vielleicht kann sich Rudi ja mal dazu äußern?
Ich bin da jetzt aber raus, mein Hotfix funktioniert erstmal für SEO42, da ich yRewrite nicht nutze ist mir das mit der Kompatibilität jetzt erstmal egal :P

**Comment by dpf-dd** [comment]
Wäre das hier besser?

Korrektur Frontend-Link (Link öffnet in neuem Tab):
Zeile 36:
`$return .= '<a href="' . seo42::getFullUrl($list->getValue('article_id'), $list->getValue('clang')) . '" target="_blank">Frontend</a>';`

**Comment by tbaddade** [comment]
seo42 ist nicht installiert, wenn man yrewrite verwendet ;)

**Comment by dpf-dd** [comment]
Stimmt. Dann gebe ich hiermit auf... Mir reicht die gefrickelte SEO42-Lösung... :P

**Comment by DanielWeitenauer** [comment]
Hi, mal eine Verständnisfrage: ist es nicht eigentlich so, dass yRewrite hier aus der Reihe tanzt? 
Ohne Rewriter erzeugt rex_getUrl auch nur relative URL, genauso wie rexseo und seo42.
Daher wäre es doch sinnvoll, eher auf den erwartbaren Standard als die Ausnahme einzugehen?

**Comment by alexplusde** [comment]
Da habe ich ja was angezettelt hier...

Da url_control ein Plugin für SEO42 ist, ist seo42::getFullUrl() ja immer mit dabei, selbst wenn das Rewrite aus SEO42 deaktiviert ist. Selbst wenn man SEO42 installiert hat, aber nicht den Rewriter von SEO42 aktiviert hat, bekommt man da doch den korrekten Link zum Frontend.

Selbst wenn yrewrite aktiviert ist (falls man die beiden überhaupt parallel verwenden kann/will), liefert seo42::getFullUrl() doch die richtige URL aus, oder?

Daher müsste doch dpf-dds letzter Vorschlag korrekt sein. 
In jedem Fall ist eine gefühlt 95% Verbesserung ja notwendig, denn im Moment geht der Link zum Frontend nicht.

**Comment by DanielWeitenauer** [comment]
Hi,
url_control soll ja als plugin für drei verschiedene Rewriter funktionieren, daher kann man nicht davon ausgehen, dass addonspezifische Funktionen vorhanden sind.
Zur Zeit wird davon ausgegangen, dass absolute URL erzeugt werden, das macht im Moment aber nur yRewrite. Daher müsste eine Weiche für yRewrite eingefügt werden, um konform mit der ursprünglichen Funktionsweise von rex_getUrl zu bleiben, ja von den anderen Rewritern berücksichtigt wird (da verweisen im Backend Links auch zu redaxo/...).

```php
if ($REX['ADDON']['url_control']['rewriter'] == 'yrewrite') {
     $return .= '<a href="' . rex_getUrl($list->getValue('article_id'), $list->getValue('clang')) . '" target="_blank">Frontend</a>';
} else {
     $return .= '<a href="' . $REX['HTDOCS_PATH'] . rex_getUrl($list->getValue('article_id'), $list->getValue('clang')) . '" target="_blank">Frontend</a>';
}
```

**Comment by alexplusde** [comment]
Ach so, das Plugin läuft also mit verschiedenen Addons. Das hatte ich nicht im Blick.
