### ISSUE TITLE
Link-Generierung nach Cache löschen fehlerhaft

### ISSUE THREAD

**Issue by dpf-dd** [tbaddade/redaxo_plugin_url_control#23]
Ein kleiner Fehler ist mir noch aufgefallen, folgendes Verhalten habe ich beobachtet und nervt mich total:

Generierter url_control-Link, der tadellos funktioniert:
http://www.test.de/kategorie1/kategorie2/artikel3.html

Jetzt lösche ich im Redaxo-Backend aus irgendeinem Grund mal den Cache und reloade die Frontend-Ansicht.
Leider sieht der generierte Link jetzt so aus:
http://www.test.de/1-0/kategorie2/artikel3.html

Das Problem lässt sich dann dadurch beheben, dass ich unter "URL erzeugen" im url_control Abschnitt bei SEO42 einfach irgendeine generierte URL öffnen und neu abspeichere (ohne Änderungen, einfach nochmal überspeichern). Scheinbar wird dann im Hintergrund wieder iwas geschrieben, sodass die Links wieder korrekt laufen => Nach einem Reload im Frontend ist die Ausgabe wieder korrekt: http://www.test.de/kategorie1/kategorie2/artikel3.html

Gibt es da einen Fix, der mir diesen umständlichen Weg spart. Das vergisst man nämlich gern mal und es ist ja auch nicht unbedingt Sinn der Sache, nach jedem Cache leeren die url_controls neu abzuspeichern :(

Vielen Dank und
MfG Stefan / dpf_dd

**Comment by tbaddade** [comment]
Die Urls werden bereits generiert, dass heiß es passiert schon mal was nach dem Cache löschen. Das Problem liegt denke ich darin, wenn UrlControl die Url generieren will [1], dass seo42 zu diesem Zeitpunkt keine Url bereitstellt. Die Urls von seo42 werden m.E. erst kurz danach generiert. EP Problematik.

Was du testen könntest um das Problem zu bestätigen.

1/ Gehe in diese Methode
https://github.com/tbaddade/redaxo_plugin_url_control/blob/master/lib/url_generate.php#L89
und setze ein `echo '<pre>UrlControl</pre>';` ein

2/ Gehe in diese Methode
https://github.com/RexDude/seo42/blob/685cf3c4a00840496dfcbddafcb0a1540e871136/classes/class.seo42_rewrite.inc.php#L471
und setze ein `echo '<pre>seo42</pre>';` ein

3/ Cache löschen

4/ Welche Reihenfolge erscheint im Backend?

[1] https://github.com/tbaddade/redaxo_plugin_url_control/blob/master/lib/url_generate.php#L89

**Comment by dpf-dd** [comment]
OK, habs mal nach deiner Anleitung getestet und kann das definitiv bestätigen - du scheinst richtig zu liegen mit der Diagnose...

Ich erzeuge aktuell 4 URLs per url_control und die echo-Reihenfolge wird so ausgegeben:

UrlControl
UrlControl
UrlControl
UrlControl
seo42

OK. Fehler ist eingegrenzt... Gibt es eine schnelle Lösung oder ist das u.a. jetzt auch ein programmlogisches Problem, was adhoc nicht lösbar? :D

**Comment by tbaddade** [comment]
Du könntest das ausprobieren

Hier 
https://github.com/tbaddade/redaxo_plugin_url_control/blob/master/config.inc.php#L114

`REX_EXTENSION_EARLY` mit `REX_EXTENSION_NORMAL` ersetzen

Solltest danach aber alles prüfen ob die Urls (das Pathfile) noch korrekt erstellt werden.

**Comment by dpf-dd** [comment]
OK, habe es wie beschrieben ausprobiert... Leider tut sich da gar nichts. Der Fehler tritt nach wie vor auf und die URL wird nicht richtig umgewandelt :(

PS: Kannst du den Fehler bei dir reproduzieren? Ich stutze gerade, warum das noch niemanden aufgefallen ist, denn Cache leeren braucht man ja öfter mal...

**Comment by tbaddade** [comment]
Du meinst die Ausgabe ist nach wie vor
```
UrlControl
UrlControl
UrlControl
UrlControl
seo42
```
