### ISSUE TITLE
Links funktionieren bei Subfoldern nicht richtig

### ISSUE THREAD

**Issue by DanielWeitenauer** [tbaddade/redaxo_plugin_url_control#25]
Hi,

Dadurch dass hier https://github.com/tbaddade/redaxo_plugin_url_control/blob/master/lib/url_control.php#L115
abschließende Slashes aus der Server-Url entfernt werden wird ein Link immer zu einem Server-relativen '/cat/art/...' umgeschrieben, dadurch gehen Subfolder, die in $REX['SERVER'] eingetragen sind verloren. Der führende Slash sollte für eine echte relative URL daher entfallen.

**Comment by tbaddade** [comment]
So richtig verstehe ich noch nicht das Problem. Du merkst an, dass der abschließende Slash entfernt wird, willst aber das der führende Slash entfällt?

**Comment by DanielWeitenauer** [comment]
Es wird der abschließenden Slash aus dem String gelöscht, der dann aus der URL entfernt wird. Dadurch hat die zurückgegebene URL vorne noch einen Slash und ist nicht relativ.
Also aus der URL ```http://url.de/subfolder/kategorie/artikel``` wird ```http://url.de/subfolder``` entfernt und ```/kategorie/artikel``` zurückgegeben. Dadurch zeigt der Link dann aber auf ```http://url.de/kategorie/artikel``` und wird natürlich nicht gefunden. Eigentlich müsste ```kategorie/artikel``` zurückgegeben werden.

Die Zeile 115 müsste daher 
```
$server = self::getServer();
```
lauten, damit es auch mit Subfoldern klappt. Gibt es einen Grund, warum Du den abschließenden Slash nicht löschst?

**Comment by DanielWeitenauer** [comment]
Sorry, falscher Knopf.

**Comment by DanielWeitenauer** [comment]
Ich räume meine Issues auf und schließe hier, weil es inzwischen Redaxo 5 gibt.
