### ISSUE TITLE
SSL Problem

### ISSUE THREAD

**Issue by Toge360** [tbaddade/redaxo_plugin_url_control#27]
Hallo,
habe gerade festgestellt, dass bei aktiviertem SSL die URLs zwar korrekt umgewandelt werden, die jeweiligen Artikel jedoch nicht gefunden werden (404).

Sobald SSL deaktiviert ist, funktioniert es ohne Probleme.

Gibt es dazu schon Informationen oder ist das Problem bekannt?

Viele Grüße
Tobi

Plugin: SEO42 AddOn für REDAXO 4.5+
redaxo_plugin_url_control: die aktuelle Version von hier

**Comment by georgkaser** [comment]
Problem ist bekannt, hatte es ebenfalls. Thomas hat mir geholfen, folgendes ist zu ändern:

Bei Zeile 135 im file /lib/url_control.php bitte auf 
`return $protocol . '://' . $_SERVER['SERVER_NAME'] . $_SERVER['REQUEST_URI'];`
ändern.

**Comment by Toge360** [comment]
Super, danke für den Tipp! Hat funktioniert.

**Comment by ghost** [comment]
Warum wird der bug nicht gefixt?
